### ISSUE TITLE
Polymer 2.x update

### ISSUE THREAD

**Issue by rgreinho** [LostInBrittany/granite-clipboard#6]
I needed this component to work with polymer 2.x, so following the [upgrade guide], I upgraded your component to a [legacy element], then to a [class-based element].

Would you be interested in creating new branches for your project so that I can submit PRs to share the updates?

I would propose reorganizing the branches like this:

* `master` -> Polymer 2.x class-based element
* `polymer-2-legacy` -> Polymer 2.x legacy element
* `polymer-1.x` -> The current master branch

[upgrade guide]: https://www.polymer-project.org/2.0/docs/upgrade
[legacy element]: https://github.com/rgreinho/granite-clipboard/tree/polymer-2-legacy
[class-based element]: https://github.com/rgreinho/granite-clipboard/tree/polymer-2-class-based

**Comment by LostInBrittany** [comment]
Hi! 

For the moment I prefer if the master branch is the hybrid (legacy) mode, as it works on both setups (Polymer 1.x and 2.x).

I have already done the hybridation of many of my elements, but I hadn't found time to upgrade this one, so I'm doing it now :)

I'm also created a polymer-2.x branch in order to receive a PR with your class based element, thanks a lot for doing it !

**Comment by LostInBrittany** [comment]
Branch `polymer-2.x` created :)
